# http://docs.travis-ci.com/user/languages/c/
language: c
sudo: true  # apt packages aren't whitelisted (yet?)
addons:
  apt:
    packages:
    - libsqlite3-dev
    - librdf0-dev
    - librdf-storage-sqlite
    # - raptor2-utils
compiler:
  - clang
  - gcc
script: sh test/run.sh
