# http://docs.travis-ci.com/user/languages/c/
language: c
sudo: false
addons:
  apt:
    packages:
    - librdf0-dev
    - librdf-storage-sqlite
    # - raptor2-utils
compiler:
  - gcc
  - clang
script: make -C test test
